version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: djangodock_nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: djangodock_server
    command: gunicorn djangodock.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    # ports:
      # - 8000:8000
      # we dont port to host, we just expose to nginx
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: djangodock_db
    ports:
      - 5432:5432
    volumes:
      - db_data_prod:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.prod

volumes:
  db_data_prod:
  static_volume:
  media_volume: